
package Server_client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.6-1b01 
 * Generated source version: 2.2
 * 
 */
@WebService(name = "GenerickiKontrolerServer", targetNamespace = "http://Server/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface GenerickiKontrolerServer {


    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns java.lang.Long
     * @throws Exception_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "registrujKorisnika", targetNamespace = "http://Server/", className = "Server_client.RegistrujKorisnika")
    @ResponseWrapper(localName = "registrujKorisnikaResponse", targetNamespace = "http://Server/", className = "Server_client.RegistrujKorisnikaResponse")
    public Long registrujKorisnika(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1)
        throws Exception_Exception
    ;

}
